version: "3"

services: 
  server:
    image: personal-blog
    restart: always
    ports:
      - "3007:3007"
  db:
    image: mysql:8
    container_name: mysql_8
    restart: always
    ports:
      - "33069:3306"
    environment:
      MYSQL_DATABASE: 'my_db_01'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes: 
      - data:/var/lib/mysql
volumes:
  data: